name: Test floatrunner.nvim

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.11.0

      - name: Run tests
        run: make test
